SELECT 
e.EMPLOYEE_ID
,e.FIRST_NAME
,e.LAST_NAME
,j.JOB_TITLE
,j.MIN_SALARY
,j.MAX_SALARY
,e.SALARY
,e.MANAGER_ID
,e2.FIRST_NAME
,dl.COUNTRY_NAME
,dl.CITY
,dl.STREET_ADDRESS
FROM
HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON e.JOB_ID = j.JOB_ID
LEFT JOIN HR.EMPLOYEES e2 ON e.MANAGER_ID = e2.EMPLOYEE_ID
LEFT JOIN (SELECT d.DEPARTMENT_ID,
  d.DEPARTMENT_NAME DEPARTMENT_NAME,
  l.CITY CITY,
  l.STREET_ADDRESS STREET_ADDRESS,
  c.COUNTRY_NAME COUNTRY_NAME
FROM HR.COUNTRIES c
RIGHT JOIN HR.LOCATIONS l
ON l.COUNTRY_ID = c.COUNTRY_ID
RIGHT JOIN HR.DEPARTMENTS d
ON d.LOCATION_ID = l.LOCATION_ID) dl ON e.DEPARTMENT_ID = dl.DEPARTMENT_ID
order by 1