INSERT INTO HR.BADROOM
(ID, CHAIR, BAD)
VALUES (HR.BADROOM_SEQ.NEXTVAL, 2, 1);

INSERT INTO HR.BATHROOM
(ID, CHAIR, TOILET)
VALUES (HR.BATHROOM_SEQ.NEXTVAL, 2, 1);

INSERT INTO HR.FURNITURE
(ID, CHAIR, MATERIAL)
VALUES (HR.FURNITURE_SEQ.NEXTVAL, 2, 'Wood');

INSERT INTO HR.HOUSEFURNITURE
(ID, CHAIR, TVTABLE)
VALUES (HR.HOUSEFURNITURE_SEQ.NEXTVAL, 1, 1);

INSERT INTO HR.KIDSROOM
(ID, CHAIR, CHILDRENLIGHTTABLE)
VALUES (HR.KIDSROOM_SEQ.NEXTVAL, 4, 1);

INSERT INTO HR.MYEXCEPTION
(ID, TEMPERATURE)
VALUES (HR.MYEXCEPTION_SEQ.NEXTVAL, 24);

INSERT INTO HR.OUTSIDEFURNITURE
(ID, GARDENSWING, HAMMOK)
VALUES (HR.BADROOM_SEQ.NEXTVAL, 2, 2);

INSERT INTO HR.SPECIALFURNITURE
(ID, COMPUTERCHAIR, COMPUTERTABLE)
VALUES (HR.BADROOM_SEQ.NEXTVAL, 22, 28);