SET  SERVEROUTPUT ON
DECLARE
  ID_VAL INTEGER := -1;
BEGIN
INSERT INTO HR.AUTHORS(ID, FULL_NAME, PHONE, B_YEAR) VALUES (HR.AUTHORS_SEQ.NEXTVAL,'Ivan Petrov', '7201413',1973)

RETURNING HR.AUTHORS.ID INTO ID_VAL;
DBMS_OUTPUT.PUT_LINE('Добавлена запись id ='||TO_CHAR(ID_VAL));
END;