SELECT 
EMP.EMPLOYEE_ID ,  EMP.FIRST_NAME , EMP.LAST_NAME , EMP.EMAIL,
EMP.PHONE_NUMBER, EMP.HIRE_DATE, EMP.JOB_ID , EMP.SALARY, 
EMP.COMMISSION_PCT, EMP.MANAGER_ID , EMP.DEPARTMENT_ID , 
EMP.MANAGER_ID , HR.COUNTRIES.COUNTRY_NAME, HR.LOCATIONS.CITY , 
HR.JOB_HISTORY.START_DATE
FROM HR.EMPLOYEES EMP
LEFT JOIN HR.JOBS ON EMP.JOB_ID = HR.JOBS.JOB_ID
LEFT JOIN HR.DEPARTMENTS ON EMP.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
LEFT JOIN HR.DEPARTMENTS ON EMP.MANAGER_ID = HR.DEPARTMENTS.MANAGER_ID
LEFT JOIN HR.LOCATIONS ON HR.DEPARTMENTS.LOCATION_ID = HR.LOCATIONS.LOCATION_ID
LEFT JOIN HR.COUNTRIES ON HR.LOCATIONS.COUNTRY_ID = HR.COUNTRIES.COUNTRY_ID
LEFT JOIN HR.JOB_HISTORY ON EMP.EMPLOYEE_ID = HR.JOB_HISTORY.EMPLOYEE_ID
ORDER BY JOB_ID;