SELECT
DEPA.DEPARTMENT_ID AS ID
,DEPA.DEPARTMENT_NAME AS NAME
,LOCA.STREET_ADDRESS AS STREET
,LOCA.CITY AS CITY
,lOCA.LOCATION_ID
FROM HR.DEPARTMENTS DEPA
LEFT JOIN HR.LOCATIONS LOCA ON DEPA.LOCATION_ID = lOCA.LOCATION_ID;