SELECT
   DEP.DEPARTMENT_ID
  ,EMP.EMPLOYEE_ID
  ,EMP.FIRST_NAME
  --,EMP.JOB_ID --мсфмн блеярн гмювемхъ ID пюяьхтпнбюрэ гмювемхе хг JOB_TITLE
  --оняке LEFT JOIN HR.JOBS JB ON EMP.JOB_ID = JB.JOB_ID
  --лнфмн апюрэ гмювемхъ хг опхянедхмнмни рюакхжш
  ,JB.JOB_TITLE
  ,JB.MIN_SALARY
  ,JB.MAX_SALARY
  --
  ,EMP.SALARY AS EMPL_SALARY
  ,EMP.MANAGER_ID
  ,EMP2.FIRST_NAME
FROM
HR.EMPLOYEES EMP
LEFT JOIN HR.JOBS JB ON EMP.JOB_ID = JB.JOB_ID
LEFT JOIN HR.EMPLOYEES EMP2 ON EMP.MANAGER_ID = EMP2.EMPLOYEE_ID
LEFT JOIN HR.DEPARTMENTS DEP ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID

ORDER BY EMP.EMPLOYEE_ID