ќпределите есть ли отделы, в которых работают сотрудники, неподчин€ющиес€ руководителю отдела
SELECT 

  DPT.DEPARTMENT_NAME
FROM HR.EMPLOYEES EMP
LEFT JOIN HR.DEPARTMENTS DPT ON DPT.DEPARTMENT_ID=EMP.DEPARTMENT_ID
LEFT JOIN HR.JOBS JBS ON JBS.JOB_ID=EMP.JOB_ID
WHERE EMP.MANAGER_ID IS NULL
GROUP BY  DPT.DEPARTMENT_NAME