--Выведите список менеджеров и названия отделов, которыми они руководят
SELECT 
  EMP.FIRST_NAME,
  EMP.LAST_NAME,
  EMP.MANAGER_ID,
 DPT.DEPARTMENT_NAME
FROM HR.EMPLOYEES EMP
LEFT JOIN HR.DEPARTMENTS DPT ON DPT.DEPARTMENT_ID=EMP.DEPARTMENT_ID
WHERE EMP.MANAGER_ID>0