INSERT INTO HR.BOOK(TITLE, AUTHORS_Id, ID , P_YEAR) VALUES ('Сказка', -1, -1, 2001 );
INSERT INTO HR.BOOK (TITLE, AUTHORS_Id, ID) VALUES ('Колобок', -2, -2);
INSERT INTO HR.BOOK (TITLE, AUTHORS_Id, ID , P_YEAR) VALUES ('Букварь', -3, -3, 2008);