SET SERVEROUTPUT ON
DECLARE 
  ID_VAL INTEGER := -1;
  
BEGIN
  INSERT INTO HR.AUTHORS (ID,FULL_NAME,PHONE,B_YEAR) 
  VALUES  (HR.AUTHORS_SEQ.NEXTVAL, 'IVAN PETROV','0989898', 1973)
  RETURNING HR.AUTHORS.ID INTO ID_VAL;
  DBMS_OUTPUT.PUT_LINE('днаюбкемю гюохяэ ID = '|| TO_CHAR(ID_VAL));
END;