SELECT DPR.DEPARTMENT_NAME AS мюгбюмхе
  , DPR.DEPARTMENT_ID AS ID
  , LCT.STATE_PROVINCE AS леярнонкнфемхе
  , LCT.CITY AS цнпнд
  , LCT.STREET_ADDRESS AS скхжю
FROM HR.DEPARTMENTS DPR
LEFT JOIN HR.LOCATIONS LCT ON DPR.LOCATION_ID = LCT.LOCATION_ID
