SELECT 
    EMP.FIRST_NAME AS хлъ_янрпсдм
  , EMP.LAST_NAME AS тюлхкхъ_янрпсдм
  , EMP.SALARY AS го
  , DPM.DEPARTMENT_NAME AS ондпюгдекемхе
  , CNT.COUNTRY_NAME AS  ярпюмю
  , JBS.JOB_TITLE AS днкфмнярэ
  , EMPM.FIRST_NAME AS хлъ_мювюкэм
  , EMPM.LAST_NAME AS тюлхкхъ_мювюкэм
FROM HR.EMPLOYEES EMP
LEFT JOIN HR.DEPARTMENTS DPM ON EMP.DEPARTMENT_ID = DPM.DEPARTMENT_ID
LEFT JOIN HR.LOCATIONS LTN ON DPM.LOCATION_ID = LTN.LOCATION_ID
LEFT JOIN HR.COUNTRIES CNT ON LTN.COUNTRY_ID = CNT.COUNTRY_ID
LEFT JOIN HR.JOBS JBS ON EMP.JOB_ID = JBS.JOB_ID
LEFT JOIN HR.EMPLOYEES EMPM ON EMP.MANAGER_ID =  EMPM.EMPLOYEE_ID
ORDER BY EMP.EMPLOYEE_ID
