--Список отделов, в которых работают сотрудники, на должностях, с оплатой более 12000
SELECT 
/*EMP.EMPLOYEE_ID,
  EMP.FIRST_NAME,
  EMP.LAST_NAME,
  EMP.EMAIL,
  EMP.PHONE_NUMBER,
  EMP.HIRE_DATE,
  EMP.JOB_ID,
  EMP.SALARY,
  EMP.COMMISSION_PCT,
  EMP.MANAGER_ID,
  EMP.DEPARTMENT_ID,
*/  DPT.DEPARTMENT_NAME
FROM HR.EMPLOYEES EMP
LEFT JOIN HR.DEPARTMENTS DPT ON DPT.DEPARTMENT_ID=EMP.DEPARTMENT_ID
WHERE EMP.SALARY>12000
GROUP BY DPT.DEPARTMENT_NAME