--Выведите список отделов и среднюю заработную плату в нем
SELECT 
 SUM( EMP.SALARY)/COUNT(EMP.DEPARTMENT_ID),
  DPT.DEPARTMENT_NAME
FROM HR.EMPLOYEES EMP
LEFT JOIN HR.DEPARTMENTS DPT ON DPT.DEPARTMENT_ID=EMP.DEPARTMENT_ID
LEFT JOIN HR.JOBS JBS ON JBS.JOB_ID=EMP.JOB_ID
WHERE EMP.DEPARTMENT_ID>0
GROUP BY  DPT.DEPARTMENT_NAME