Выведите список отделов с указанием общего бюджета на оплату труда его сотрудников
SELECT 
 SUM( EMP.SALARY),
  DPT.DEPARTMENT_NAME
FROM HR.EMPLOYEES EMP
LEFT JOIN HR.DEPARTMENTS DPT ON DPT.DEPARTMENT_ID=EMP.DEPARTMENT_ID
LEFT JOIN HR.JOBS JBS ON JBS.JOB_ID=EMP.JOB_ID

GROUP BY  DPT.DEPARTMENT_NAME