--Выведите список отделов и количество сотрудников каждом из отделов
SELECT 
COUNT(EMP.DEPARTMENT_ID),

 DPT.DEPARTMENT_NAME
FROM HR.EMPLOYEES EMP
LEFT JOIN HR.DEPARTMENTS DPT ON DPT.DEPARTMENT_ID=EMP.DEPARTMENT_ID
GROUP BY DPT.DEPARTMENT_NAME