CREATE TABLE HR.GAS
(
  ID INT NOT NULL , NAME VARCHAR2(100) NOT NULL , PPICE_STO INT NOT NULL , PRICE INTEGER NOT NULL , ML INTEGER NOT NULL , NAME_FRUIT NCHAR(20),
  KALORIE INT , SUGAR INT, AMOUNT INT NOT NULL, COFEIN_MG INT, CO2 INT
);
