CREATE TABLE HR.JUICE
(
  ID INT NOT NULL , NAME VARCHAR2(100) NOT NULL , PPICE_STO INT NOT NULL , PRICE INTEGER NOT NULL , ML INTEGER NOT NULL , NAME_FRUIT NCHAR(20) NOT NULL ,
  KALORIE INT , SUGAR INT, AMOUNT INT NOT NULL
);
