CREATE TABLE HR.VINE
(
  ID INT NOT NULL , NAME VARCHAR2(100) NOT NULL , PPICE_STO INT NOT NULL , PRICE INTEGER NOT NULL , ML INTEGER NOT NULL , 
  KALORIE INT , SUGAR INT, AMOUNT INT NOT NULL, SPIRT INT, COUNTRY_NAME  VARCHAR2(20)
);
