CREATE SEQUENCE HR.BADROOM_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE HR.BATHROOM_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE HR.FURNITURE_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE HR.HOUSEFURNITURE_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE HR.KIDSROOM_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE HR.MYEXCEPTION_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE HR.OUTSIDEFURNITURE_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE HR.SPECIALFURNITURE_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;