CREATE SEQUENCE MYPROJ.BADROOM_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE MYPROJ.BATHROOM_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE MYPROJ.FURNITURE_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE MYPROJ.HOUSEFURNITURE_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE MYPROJ.KIDSROOM_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE MYPROJ.MYEXCEPTION_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE MYPROJ.OUTSIDEFURNITURE_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE MYPROJ.SPECIALFURNITURE_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1;