SELECT HR.BADROOM_SEQ.NEXTVAL FROM DUAL;

SELECT HR.BATHROOM_SEQ.NEXTVAL FROM DUAL;

SELECT HR.FURNITURE_SEQ.NEXTVAL FROM DUAL;

SELECT HR.HOUSEFURNITURE_SEQ.NEXTVAL FROM DUAL;

SELECT HR.KIDSROOM_SEQ.NEXTVAL FROM DUAL;

SELECT HR.MYEXCEPTION_SEQ.NEXTVAL FROM DUAL;

SELECT HR.OUTSIDEFURNITURE_SEQ.NEXTVAL FROM DUAL;

SELECT HR.SPECIALFURNITURE_SEQ.NEXTVAL FROM DUAL;