SELECT MYPROJ.BADROOM_SEQ.NEXTVAL FROM DUAL;

SELECT MYPROJ.BATHROOM_SEQ.NEXTVAL FROM DUAL;

SELECT MYPROJ.FURNITURE_SEQ.NEXTVAL FROM DUAL;

SELECT MYPROJ.HOUSEFURNITURE_SEQ.NEXTVAL FROM DUAL;

SELECT MYPROJ.KIDSROOM_SEQ.NEXTVAL FROM DUAL;

SELECT MYPROJ.MYEXCEPTION_SEQ.NEXTVAL FROM DUAL;

SELECT MYPROJ.OUTSIDEFURNITURE_SEQ.NEXTVAL FROM DUAL;

SELECT MYPROJ.SPECIALFURNITURE_SEQ.NEXTVAL FROM DUAL;