INSERT INTO MYPROJ.BADROOM
(ID, CHAIR, BAD)
VALUES (MYPROJ.BADROOM_SEQ.NEXTVAL, 2, 1);

INSERT INTO MYPROJ.BATHROOM
(ID, CHAIR, TOILET)
VALUES (MYPROJ.BATHROOM_SEQ.NEXTVAL, 2, 1);

INSERT INTO MYPROJ.FURNITURE
(ID, CHAIR, MATERIAL)
VALUES (MYPROJ.FURNITURE_SEQ.NEXTVAL, 2, 'Wood');

INSERT INTO MYPROJ.HOUSEFURNITURE
(ID, CHAIR, TVTABLE)
VALUES (MYPROJ.HOUSEFURNITURE_SEQ.NEXTVAL, 1, 1);

INSERT INTO MYPROJ.KIDSROOM
(ID, CHAIR, CHILDRENLIGHTTABLE)
VALUES (MYPROJ.KIDSROOM_SEQ.NEXTVAL, 4, 1);

INSERT INTO MYPROJ.MYEXCEPTION
(ID, TEMPERATURE)
VALUES (MYPROJ.MYEXCEPTION_SEQ.NEXTVAL, 24);

INSERT INTO MYPROJ.OUTSIDEFURNITURE
(ID, GARDENSWING, HAMMOK)
VALUES (MYPROJ.BADROOM_SEQ.NEXTVAL, 2, 2);

INSERT INTO MYPROJ.SPECIALFURNITURE
(ID, COMPUTERCHAIR, COMPUTERTABLE)
VALUES (MYPROJ.BADROOM_SEQ.NEXTVAL, 22, 28);