SELECT 
    EMP.FIRST_NAME
  , EMP.LAST_NAME 
  , EMP.SALARY 
  , DEM.DEPARTMENT_NAME
  , CNT.COUNTRY_NAME
  , JB.JOB_TITLE
  , EMP2.FIRST_NAME
  , EMP2.LAST_NAME
FROM HR.EMPLOYEES EMP

LEFT JOIN HR.DEPARTMENTS DEP ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
LEFT JOIN HR.LOCATIONS LOC ON DPM.LOCATION_ID = LOC.LOCATION_ID
LEFT JOIN HR.COUNTRIES CNT ON LTN.COUNTRY_ID = CNT.COUNTRY_ID
LEFT JOIN HR.JOBS JB ON EMP.JOB_ID = JB.JOB_ID
LEFT JOIN HR.EMPLOYEES EMP2 ON EMP.MANAGER_ID =  EMP2.EMPLOYEE_ID

ORDER BY EMP.EMPLOYEE_ID
