SET SERVEROUTPUT ON
DECLARE
  ID_VAL INTEGER :=-1;
BEGIN
  INSERT INTO HR.AUTHORS (ID,FULL_NAME,ALIAS,B_YEAR,PHONE,EMAIL) VALUES
  (HR.AUTHORS_SEQ.NEXTVAL, 'Petrov','Kasparov', 1977, '+03800502563478', 'sdfgs@sdf.rt')
  RETURNING HR.AUTHORS.ID INTO ID_VAL;
  
  DBMS_OUTPUT.PUT_LINE('Добавлена запись ID='||TO_CHAR(ID_VAL));
END;
  