SET SERVEROUTPUT ON
DECLARE
  I INTEGER :=0;
    COUNTING INTEGER :=0;
BEGIN
  WHILE (I<=50) LOOP
    I:=I+1;
    COUNTING := COUNTING+I;
  END LOOP;
    DBMS_OUTPUT.PUT_LINE('COUNTING ALL='||TO_CHAR(COUNTING));
  
  
  I:=0;
  COUNTING:=0;
  WHILE (I<=50) LOOP
    I:=I+2;
    COUNTING := COUNTING+I;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('COUNTING 2='||TO_CHAR(COUNTING));
  
END;
