INSERT INTO HR.BOOKS
(TITLE, AUTHOR_ID, ID, P_YEAR)
VALUES('Kolobok', -1, -1, 1995 );

INSERT INTO HR.BOOKS
(TITLE, AUTHOR_ID, ID, P_YEAR)
VALUES('Belosnejka', -2, -2, 1876);

INSERT INTO HR.BOOKS
(TITLE, AUTHOR_ID, ID, P_YEAR)
VALUES('Mumu', -1, -3, 1845);