SET SERVEROUTPUT ON
DECLARE
ID_VAL INTEGER := -1;

BEGIN 
  INSERT INTO HR.AUTHORS
  (ID, FULL_NAME, PHONE, B_YEAR)
  VALUES (HR.AUTHORS_SEQ.NEXTVAL, 'Ivan Petrov', '+380667894523', 1987)
  
  RETURNING HR.AUTHORS.ID INTO ID_VAL;
  DBMS_OUTPUT.PUT_LINE('Добавлена запись ID = '||TO_CHAR(ID_VAL));
END;